### ISSUE TITLE
select one stop or two stops on the same route

### ISSUE THREAD

**Issue by EddyIonescu** [trynmaps/opentransit-map#39]
Selecting a stop will be needed in order to show reliability data for that stop - while selecting two would be needed for showing travel-times/speeds/reliability within that segment.
The flow could work like this:
1. selecting a stop selects it
2. selecting another stop on the same route (edit 5/16/18: and direction) creates a segment of the route
3. selecting any other stop will make that stop alone selected -> go to step 1

Part 1: Print out to console.log the selected stop IDs (either 0, 1, or 2 can be printed out)
Part 2: Make selected stops a different colour (or icon)
Part 3: Get the subsection of the route (if two stops are selected)
Part 4: Draw that subsection (if two stops are selected)

Let's have a PR for each part and merge before moving onto the next one. Also gave this the "mini-project" tag (think of it as a "Story" in JIRA :)

**Comment by ckrajewski** [comment]
@EddyIonescu  Will look into it

**Comment by ckrajewski** [comment]
@EddyIonescu 
For this issue, I'm assuming you would like the route segment highlighted in another color on the map correct? Between the two stops?
And should the user be able to select stops from different routes at once (i.e max two stops per route?)

**Comment by EddyIonescu** [comment]
@ckrajewski yeah, the colour can be anything (hardcoding it in the css would be great). No, for simplicity, I'd leave it either a) two stops in a route selected b) one stop selected c) no stops selected

**Comment by EddyIonescu** [comment]
Also, this library seems good for getting the line to draw along the route (it's used in the API code) - http://turfjs.org/docs#lineSegment

**Comment by EddyIonescu** [comment]
Update: split this issue into 4 parts (so there'll be 4 small PRs that should be easy to review & merge) as to move faster & not get stuck

**Comment by ckrajewski** [comment]
Cool I like the idea of breaking it up.
I have the first pass of PR up.
Logic looks OK, but I'm to see  if it's possible to clean up some parts up a little.
https://github.com/trynmaps/tryn-react/pull/47/files
