### ISSUE TITLE
Error: Failed prop type: The prop `trynState.isRequired` is marked as required in `Map`,...

### ISSUE THREAD

**Issue by komali2** [trynmaps/opentransit-map#60]
See https://github.com/trynmaps/tryn-react/issues/58 for more information on the bit of code that's causing this issue. 

Error is: 

```
Warning: Failed prop type: The prop `trynState.isRequired` is marked as required in `Map`, but its value is `undefined`.
    in Map (created by Relay(Map))
    in Relay(Map) (at App.jsx:49)
    in ReactRelayQueryRenderer (at App.jsx:32)
    in div (at App.jsx:60)
    in App (at index.jsx:10)
```

**Comment by EddyIonescu** [comment]
I think this happens because we explicitly pass null into Map as to load the map before it gets a response from the API. That or relay creates the component without passing in the prop defined in QueryRenderer. Closing since it's a warning that's not causing any issues.
