### ISSUE TITLE
color buses differently based on route

### ISSUE THREAD

**Issue by EddyIonescu** [trynmaps/opentransit-map#63]
eg. J would be orange
N would be blue

So I think we'd want to make a config file that has something like
```
{
   'N-Judah': #hex-for-blue,
   ...
}
```

**Comment by komali2** [comment]
Routes might change 
just do this

https://stackoverflow.com/questions/3426404/create-a-hexadecimal-colour-based-on-a-string-with-javascript

Hash arbitrary strings to hex values

There's so many routes there's no way we can apply "meaningful" color to each one, at least with this the hash will ALWAYS output the same color for a given route, based on its name.

**Comment by komali2** [comment]
https://github.com/trynmaps/opentransit-map/tree/caleb/bus-colors check my WIP commit for an idea

not working for some reason, need to find out hwere color actually gets input

**Comment by EddyIonescu** [comment]
@komali2 sounds good - as long as the Muni metro routes are certain colors. Was thinking buses could all just be red - as we're not conveying much info through it (we could give R and X buses darker shades of red?)

**Comment by fruit13ok** [comment]
https://github.com/trynmaps/opentransit-map/pull/94/
