### ISSUE TITLE
Make date/time selectors more obviously separate buttons

### ISSUE THREAD

**Issue by komali2** [trynmaps/opentransit-map#66]
Right now they look and act like the same button, even though clicking on one fontawesome thing vs the other does open a different modal. 

![screenshot from 2018-06-20 19-43-47](https://user-images.githubusercontent.com/8533113/41695094-5af13b8e-74c2-11e8-9f12-89032f65b79c.png)

**Comment by akgupta89** [comment]
https://github.com/trynmaps/opentransit-map/pull/80
