### ISSUE TITLE
upgrade to react 16 and latest deck.gl+map.gl versions

### ISSUE THREAD

**Issue by EddyIonescu** [trynmaps/opentransit-map#76]
Since first making this repo, React got a huge upgrade to 16, while deck.gl had multiple major releases.  Same for Relay and GraphQL. Based on projects I started more recently, our map should lag a lot less. That said, I tried upgrading a few months ago and the zoom button broke. Still, we should update our packages. This PR tracks updating all packages such that the web-app will stay stable.

**Comment by EddyIonescu** [comment]
@komali2 I assigned this to myself, but I'm working on backend+data stuff at the moment. It's not a very fun ticket, but would you be okay with taking it on? 

It might be pretty easy - or it might break things in really mysterious ways (which will likely be the case - I'm almost certain it'll break the zoom buttons)

**Comment by komali2** [comment]
Happy to look into it for sure

**Comment by akgupta89** [comment]
I took a swing at it today, I feel I'm halfway there, I need to make some changes to yarn because of yarn.lock to be able to build it properly. I'll give it a try on the weekend.

**Comment by Tranced** [comment]
Hey is anyone still working on this? I'd like to look into taking this one on b/c hooks just came out.

**Comment by EddyIonescu** [comment]
Hey @Tranced, no, no one's learning on this atm. Sounds good, definitely take a shot at it!

**Comment by EddyIonescu** [comment]
Really close to finishing this, we just have to change the way we make IconLayers. The bright side is that everything should load and render much faster (it's 1.5 years worth of development!). Closing this issue since it's being resumed here: https://github.com/trynmaps/opentransit-map/issues/106
