### ISSUE TITLE
add dropdown to choose different cities

### ISSUE THREAD

**Issue by EddyIonescu** [trynmaps/opentransit-map#87]
Currently OpenTransit only works for San Francisco. We want to add support for other cities, starting with Toronto. This ticket is making a dropdown for choosing a city. It should be placed above the routes list and below the toggles.

**Comment by lukemccrae** [comment]
I'm taking a shot at this! Will have a couple questions, who can I reach out to with questions?

**Comment by lukemccrae** [comment]
I had the dev build running fine yesterday but this morning I'm getting a bunch of peer dependency errors. Do you know what could have caused this?

**Comment by lukemccrae** [comment]
I've got some peer dependency issues, even on untouched master branch. `yarn` is showing 

> warning " > bootstrap@4.0.0-beta" has unmet peer dependency "jquery@>=3.0.0".
warning " > bootstrap@4.0.0-beta" has unmet peer dependency "popper.js@^1.11.0".
warning " > deck.gl@4.1.5" has incorrect peer dependency "react@0.14.x - 15.x".
warning " > deck.gl@4.1.5" has incorrect peer dependency "react-dom@0.14.x - 15.x".
warning " > eslint-config-react-app@2.0.1" has incorrect peer dependency "eslint-plugin-jsx-a11y@^5.1.1".

Also running into `Cannot read property ‘match’ of undefined` errors. I tried [https://npm.community/t/npm-err-cannot-read-property-match-of-undefined/234](this) solution of deleting package-lock.json/node_modules but I get the same errors after running `yarn`. Any advice?

**Comment by EddyIonescu** [comment]
@lukemccrae I don't see any `Cannot read property ‘match’ of undefined` errors when I run the master branch. Those warnings from yarn are okay. Did you make any code changes that resulted in that? Also, we use yarn, not npm, so that link doesn't seem relevant.

**Comment by EddyIonescu** [comment]
Also, if you want to assign yourself to this issue, accept the Github invitation I just sent and assign it to yourself - welcome!

**Comment by lukemccrae** [comment]
Thanks for your reply! I think I caused the issues by using npm. I've recloned the project and all is well :)

**Comment by EddyIonescu** [comment]
https://github.com/trynmaps/opentransit-map/pull/103
